[package]
name = "variadic"
version = "0.1.0"
authors = ["Pablo Sichert <pablo.sichert@westwing.de>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
libc = { path = "./libc" }
wasm-bindgen = "0.2"

[dev-dependencies]
wasm-bindgen-test = "0.2"
