name: CI

on:
  push:
  pull_request:

jobs:
  test-native:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1.0.6
      with:
        toolchain: nightly
        default: true
    - run: cargo test
  test-wasm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1.0.6
      with:
        toolchain: nightly
        default: true
        target: wasm32-unknown-unknown
    - uses: actions/setup-node@v1.1.0
    - run: cargo install wasm-pack
    - run: wasm-pack test --node
